
env:
	source  env/bin/activate

install:
	pip install -r requirements.txt

build:
	python setup.py sdist bdist_wheel

update-package:
	pip install git+https://github.com/Marie000/Salary_Predictor_Project.git -U
